### ISSUE TITLE
Switch from latest ST2 'dev' to 'stable'

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-k8s#49]
Currently, to pickup most recent `st2` fixes and improvements related to HA, we rely on latest `st2 X.Ydev` versions in Docker images that are built nightly.
Once we proceed our ST2 HA K8s story from `beta` -> `prod` stage, switch from using latest st2 `dev` versions to st2 `stable`.

### TODO:
- [x] `appVersion` Helm change
- [ ] Dockerfiles CI/CD build settings updates
- [ ] Announce the change and prod/GA readiness to our community.
- [ ] Docs update for https://docs.stackstorm.com/install/k8s_ha.html
- [x] https://github.com/StackStorm/stackstorm-ha README

**Comment by tarcusx** [comment]
Hi @armab 
I'm trying to deploy st2 on K8S using this repo, and seeing some issues.
For troubleshooting, I want to know where the Dockerfiles are.
As you mentioned, current images are `stackstorm/st2*:3.0dev`, but I cannot find the Dockerfiles for those images at st2-docker. DockerHub also doesn't have any information.
Could you please let me know the repo/branch?

**Comment by armab** [comment]
@tarcusx See https://github.com/StackStorm/stackstorm-ha#components which highlights the repos (https://github.com/stackstorm/st2-dockerfiles).

**Comment by armab** [comment]
The Helm charts migrated to `stable` st2 versions by default a while ago instead of using `dev` builds. Closing.
